[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FlameGraphs = "08572546-2f56-4bcf-ba4e-bab62c3a3f89"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
UnitCommitment = "64606440-39ea-11e9-0f29-3303a1d3d877"
